#!/usr/bin/env python3
"""
build_claude_slim.py — Slim CLAUDE.md variant generator (IVG-164 Wave 3, S-1).

Parses quoin/CLAUDE.md into fence-aware H1-H3 sections and splits them per a
fail-closed binary CLASSIFICATION table (keep/drop, no third state) into two
generated outputs:

  - quoin/CLAUDE.slim.md          — keep sections verbatim + a pointer index
                                     naming where each dropped section's full
                                     text now lives.
  - quoin/memory/workflow-catalog.md — every dropped section's full text
                                     verbatim, under its original heading.

Authority split (plan D-13): this script's parser is the ENUMERATION
authority (heading set, byte totals, bijectivity). The CLASSIFICATION table
below is transcribed from the architecture Appendix's `Slim classification`
column as amended by plan decisions D-07 (keep ### Communication a drop row)
and D-14 (promote ### Workflow conventions / ### Archiving completed work to
keep) — it is the CLASSIFICATION authority, not this parser. If the live
heading set disagrees with this table (a heading is unclassified, or a table
entry has no matching heading), this script aborts non-zero rather than
guessing (D-13/D-05 fail-closed).

Modes:
  (default)   write both quoin/CLAUDE.slim.md and quoin/memory/workflow-catalog.md
  --check     regenerate in memory and byte-compare against the committed
              files; exit 7 on mismatch, naming the stale file
  --dry-run   print both outputs to stdout; write nothing
  --census    emit the mechanical heading/byte table (enumeration only)

Exit codes:
  0  success
  1  a source heading has no CLASSIFICATION entry (fail-closed, roster-drift)
  2  a CLASSIFICATION entry has no matching source heading (orphan entry)
  3  duplicate heading text in the source file
  7  --check: a generated output differs from the committed file
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]  # quoin/ (repo root)
_SOURCE_ROOT = _REPO_ROOT / "quoin"

SOURCE = _SOURCE_ROOT / "CLAUDE.md"
SLIM_OUTPUT = _SOURCE_ROOT / "CLAUDE.slim.md"
CATALOG_OUTPUT = _SOURCE_ROOT / "memory" / "workflow-catalog.md"

_QUOIN_HOME_PLACEHOLDER = "__QUOIN_HOME__"

# --- Pinned generated headers (T-04, plan MAJ-2 r3 / round 4) ---------------
# HTML-comment form (never parseable as a markdown heading), zero
# __QUOIN_HOME__ occurrences, carries the file's own self-description.
SLIM_HEADER = (
    "<!-- CLAUDE.slim.md — generated by quoin/scripts/build_claude_slim.py "
    "from quoin/CLAUDE.md; do not hand-edit. Slim variant of the shared "
    "development-workflow rules: sections not needed in the main session "
    "were extracted into the memory catalog and are listed, with their "
    "destinations, in the pointer index at the end of this file. -->\n\n"
)
CATALOG_HEADER = (
    "<!-- generated by quoin/scripts/build_claude_slim.py from quoin/CLAUDE.md "
    "— do not hand-edit; this is the full text of every section dropped from "
    "CLAUDE.slim.md. -->\n\n"
)

# Pointer-index header: ONE __QUOIN_HOME__ placeholder for the whole index
# (D-01) — per-row lines carry only a bare guide filename.
INDEX_HEADER = (
    "Dropped sections live in full under " + _QUOIN_HOME_PLACEHOLDER + "/memory/ "
    "— the catalog is workflow-catalog.md; bare filenames below are siblings "
    "of it.\n"
)

# --- CLASSIFICATION table (T-04) --------------------------------------------
# Ordered mapping of exact heading-line text -> ("keep"|"drop", target-or-None).
# Transcribed from the architecture Appendix's Slim classification column as
# amended by plan D-07 (### Communication stays drop) and D-14 (two
# promotions to keep). Index targets are the D-16 round-4 POST-restructure
# derivation (never the architecture Appendix's pre-restructure column):
# rows 14 (### Task profiles), 18 (### Git workflow), and 23 (### Session
# state tracking) re-target to workflow-catalog.md because the guide that
# earned them in the Appendix no longer carries their post-restructure
# substance (or, for row 23, the substance is split across two guides and a
# single-target row cannot represent a split). Row 35 additionally re-targets
# from sleep-signals.yaml to workflow-catalog.md (round-4 critic MIN-3): the
# YAML carries the row's *data*, not its *prose* (fallback-chain narrative,
# QUOIN_SLEEP_* env-var docs) — it fails D-16's substance rule.
CLASSIFICATION: dict[str, tuple[str, str | None]] = {
    "# Development Workflow — Shared Rules": ("keep", None),
    "## Open-model routing (opt-in)": ("drop", "workflow-catalog.md"),
    "## Working Rules": ("keep", None),
    "### Git & PR Safety": ("keep", None),
    "### Communication": ("drop", "workflow-catalog.md"),
    "### Workflow conventions": ("keep", None),
    "## Project structure": ("keep", None),
    "## Task subfolder convention": ("keep", None),
    "### Multi-stage tasks": ("drop", "workflow-catalog.md"),
    "### Archiving completed work": ("keep", None),
    "## Workflow sequence": ("keep", None),
    "### Canonical flow": ("keep", None),
    "### Explicit-command rule": ("keep", None),
    "### Task profiles": ("drop", "workflow-catalog.md"),
    "## Session independence": ("drop", "workflow-catalog.md"),
    "## Common rules for all skills": ("keep", None),
    "### Branch hygiene (essential)": ("keep", None),
    "### Git workflow": ("drop", "workflow-catalog.md"),
    "### Web research": ("drop", "workflow-catalog.md"),
    "### Serena (conditional)": ("drop", "serena-activation.md"),
    "### Daily insight capture": ("drop", "workflow-catalog.md"),
    "### Lessons learned": ("drop", "workflow-catalog.md"),
    "### Session state tracking": ("drop", "workflow-catalog.md"),
    "### Cost tracking": ("drop", "cost-ledger-format.md"),
    "### Knowledge cache": ("drop", "cache-guide.md"),
    "### Tier 1 — files that always stay English (caveman-token-optimization carve-out)": (
        "drop",
        "tier1-files.md",
    ),
    "## Model assignments": ("drop", "workflow-catalog.md"),
    "### Subagent preamble (Stage 2 of pipeline-efficiency-improvements)": (
        "drop",
        "preamble-guide.md",
    ),
    "### §0 Model dispatch preamble": ("drop", "dispatch-guide.md"),
    "### §0' Pollution dispatch": ("drop", "dispatch-guide.md"),
    "### §0″ Minimum-tier guard": ("drop", "dispatch-guide.md"),
    "### §V Ground-truth verification": ("drop", "verification-guide.md"),
    "### Hooks deployed by quoin": ("drop", "hooks-table.md"),
    "### Lifecycle skills (checkpoint / end_of_day / sleep / cleanup)": (
        "drop",
        "lifecycle-guide.md",
    ),
    "### /sleep importance signals": ("drop", "workflow-catalog.md"),
    "### Workflow memory layers": ("drop", "workflow-catalog.md"),
}


class ClassificationError(RuntimeError):
    """Fail-closed error: source headings and CLASSIFICATION disagree."""


def _fence_aware_headings(text: str) -> list[tuple[int, str]]:
    """Return [(byte_offset, heading_line), ...] for real (non-fenced) H1-H3s."""
    lines = text.split("\n")
    in_fence = False
    offsets: list[tuple[int, str]] = []
    byte_pos = 0
    seen: set[str] = set()
    for ln in lines[:-1]:  # split("\n") on a trailing-newline file ends with ""
        stripped = ln.lstrip()
        if stripped.startswith("```"):
            in_fence = not in_fence
        elif not in_fence and re.match(r"^#{1,3} ", ln):
            if ln in seen:
                raise ClassificationError(f"duplicate heading text in source: {ln!r}")
            seen.add(ln)
            offsets.append((byte_pos, ln))
        byte_pos += len(ln.encode("utf-8")) + 1
    return offsets


def parse_sections(text: str) -> list[tuple[str, int, str]]:
    """Return [(heading, byte_size, section_text), ...] in source order."""
    raw = text.encode("utf-8")
    headings = _fence_aware_headings(text)
    headings.append((len(raw), "<EOF>"))
    sections = []
    for i in range(len(headings) - 1):
        start, heading = headings[i]
        end, _ = headings[i + 1]
        section_bytes = raw[start:end]
        sections.append((heading, len(section_bytes), section_bytes.decode("utf-8")))
    return sections


def classify(sections: list[tuple[str, int, str]]) -> None:
    """Fail-closed bijectivity check between source headings and CLASSIFICATION."""
    source_headings = {h for h, _, _ in sections}
    table_headings = set(CLASSIFICATION.keys())

    missing = source_headings - table_headings
    if missing:
        raise ClassificationError(
            f"{len(missing)} source heading(s) have no CLASSIFICATION entry "
            f"(fail-closed, roster-drift direction): {sorted(missing)!r}"
        )
    orphan = table_headings - source_headings
    if orphan:
        raise ClassificationError(
            f"{len(orphan)} CLASSIFICATION entr(y/ies) have no matching source "
            f"heading (orphan-entry direction): {sorted(orphan)!r}"
        )


def build_outputs(source_text: str) -> tuple[str, str]:
    """Return (slim_text, catalog_text)."""
    sections = parse_sections(source_text)
    classify(sections)

    keep_parts: list[str] = []
    drop_parts: list[str] = []
    index_rows: list[str] = []

    for heading, _size, section_text in sections:
        cls, target = CLASSIFICATION[heading]
        if cls == "keep":
            keep_parts.append(section_text)
        else:
            drop_parts.append(section_text)
            index_rows.append(f"- {heading} -> {target}\n")

    slim_text = SLIM_HEADER + "".join(keep_parts)
    # Each kept section already ends with a trailing blank line (the section
    # byte-span runs up to the next heading). Normalize to exactly one
    # trailing blank line before the index, regardless of how many blank
    # lines happened to trail the final kept section.
    slim_text = slim_text.rstrip("\n") + "\n\n"
    slim_text += INDEX_HEADER + "".join(index_rows)

    catalog_text = CATALOG_HEADER + "".join(drop_parts)

    return slim_text, catalog_text


def run_census(source_text: str) -> str:
    sections = parse_sections(source_text)
    lines = []
    keep_total = 0
    drop_total = 0
    for heading, size, _text in sections:
        cls = CLASSIFICATION.get(heading, ("???", None))[0]
        if cls == "keep":
            keep_total += size
        elif cls == "drop":
            drop_total += size
        lines.append(f"{cls:5} {size:6} {heading}")
    lines.append("---")
    lines.append(f"heading count = {len(sections)}")
    lines.append(f"keep_bytes = {keep_total}")
    lines.append(f"drop_bytes = {drop_total}")
    lines.append(f"sum = {keep_total + drop_total} vs file total {len(source_text.encode('utf-8'))}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true", help="verify committed outputs match regen")
    group.add_argument("--dry-run", action="store_true", help="print outputs, write nothing")
    group.add_argument("--census", action="store_true", help="print the mechanical heading/byte table")
    args = parser.parse_args(argv)

    source_text = SOURCE.read_text(encoding="utf-8")

    if args.census:
        try:
            sys.stdout.write(run_census(source_text))
        except ClassificationError as exc:
            print(f"build_claude_slim: {exc}", file=sys.stderr)
            return 1
        return 0

    try:
        slim_text, catalog_text = build_outputs(source_text)
    except ClassificationError as exc:
        print(f"build_claude_slim: {exc}", file=sys.stderr)
        # Distinguish the two fail-closed directions for the exit code.
        if "orphan-entry" in str(exc):
            return 2
        if "duplicate heading" in str(exc):
            return 3
        return 1

    if args.dry_run:
        sys.stdout.write("=== CLAUDE.slim.md ===\n")
        sys.stdout.write(slim_text)
        sys.stdout.write("\n=== memory/workflow-catalog.md ===\n")
        sys.stdout.write(catalog_text)
        return 0

    if args.check:
        stale = []
        if not SLIM_OUTPUT.exists() or SLIM_OUTPUT.read_text(encoding="utf-8") != slim_text:
            stale.append(str(SLIM_OUTPUT))
        if not CATALOG_OUTPUT.exists() or CATALOG_OUTPUT.read_text(encoding="utf-8") != catalog_text:
            stale.append(str(CATALOG_OUTPUT))
        if stale:
            print(
                "build_claude_slim --check: stale generated file(s): " + ", ".join(stale),
                file=sys.stderr,
            )
            return 7
        return 0

    SLIM_OUTPUT.write_text(slim_text, encoding="utf-8")
    CATALOG_OUTPUT.write_text(catalog_text, encoding="utf-8")
    print(f"Wrote {SLIM_OUTPUT}")
    print(f"Wrote {CATALOG_OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
