"""T-12 (stage 4, MAJOR-R1 structural closure): end-to-end partial-signal
propagation-contract test.

Exercises the FULL "Partial-signal propagation contract" enumerated in
current-plan.md (proc:partial-chain) with a hop-pinned sub-assertion per hop,
so a drop at ANY hop fails a DISTINCT, named assertion:

  HOP 1  dashboard_cost.provider(...)            produces cost.partial=True
  HOP 2  dashboard_model._task_summary            merge whitelist KEEPS "partial"
  HOP 3  dashboard_model.scan_tasks/task_detail    embeds the cost dict into JSON
  HOP 4  dashboard_server.py /api/tasks*           json.dumps pass-through
  HOP 5  dashboard_assets/app.js render            badge/detail/by-phase (partial)

The fixture is the shared T-08 mixed-column ledger: a resolved row + a
src=unresolved row for the SAME task, authored as RAW ledger lines (D-4 —
never generated by enabling QUOIN_INLINE_COST_CAPTURE). This drives the
REAL dashboard_cost.make_cost_provider (no fakes) through every hop.
"""
from __future__ import annotations

import http.client
import importlib.util
import json
import sys
import threading
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Load the real modules for every hop via spec_from_file_location
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parents[3]
_CORE_SCRIPTS = _REPO_ROOT / "quoin" / "core" / "scripts"
_ADAPTER_SCRIPTS = _REPO_ROOT / "quoin" / "scripts"


def _load(module_key: str, path: Path):
    if module_key in sys.modules:
        return sys.modules[module_key]
    spec = importlib.util.spec_from_file_location(module_key, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[module_key] = mod
    spec.loader.exec_module(mod)
    return mod


_dashboard_cost = _load("_t12_dashboard_cost", _ADAPTER_SCRIPTS / "dashboard_cost.py")
_dashboard_model = _load("_t12_dashboard_model", _CORE_SCRIPTS / "dashboard_model.py")
_dashboard_server = _load("_t12_dashboard_server", _ADAPTER_SCRIPTS / "dashboard_server.py")

make_cost_provider = _dashboard_cost.make_cost_provider
scan_tasks = _dashboard_model.scan_tasks
task_detail = _dashboard_model.task_detail
project_hash = _dashboard_cost.project_hash

_APP_JS_PATH = _CORE_SCRIPTS / "dashboard_assets" / "app.js"


# ---------------------------------------------------------------------------
# Fixture: shared mixed-column ledger — a resolved row + an src=unresolved
# row for the SAME task (D-4: raw ledger lines, flag stays OFF).
# ---------------------------------------------------------------------------

def _make_mixed_project(tmp_path: Path, task_name: str = "mixed-task") -> Path:
    project_root = tmp_path / "project"
    task_dir = project_root / ".workflow_artifacts" / task_name
    task_dir.mkdir(parents=True)
    ledger = task_dir / "cost-ledger.md"
    ledger.write_text(
        "# Cost Ledger — mixed-task\n"
        "res-uuid-0001 | 2026-07-27 | implement | opus | task | \"resolved\" | 0 | "
        "usd=1.25;tok=1000;src=nested_jsonl\n"
        "unres-uuid-0002 | 2026-07-27 | implement | opus | task | \"unresolved\" | 0 | "
        "tok=45;src=unresolved\n"
    )
    return project_root


def _make_resolved_zero_project(tmp_path: Path, task_name: str = "zero-task") -> Path:
    """MINOR-5/D-8 corollary fixture: a single resolved usd=0.0 row."""
    project_root = tmp_path / "project"
    task_dir = project_root / ".workflow_artifacts" / task_name
    task_dir.mkdir(parents=True)
    ledger = task_dir / "cost-ledger.md"
    ledger.write_text(
        "# Cost Ledger — zero-task\n"
        "zero-uuid-0001 | 2026-07-27 | implement | opus | task | \"resolved zero\" | 0 | "
        "usd=0.0;tok=9;src=nested_jsonl\n"
    )
    return project_root


def _start_server(project_root: Path, cost_provider):
    """Start dashboard_server in a background thread. Returns (server, thread)."""
    class _Handler(_dashboard_server.DashboardHandler):
        pass

    _Handler.project_root = project_root
    # staticmethod() is REQUIRED here — see dashboard_server.py's DashboardHandler
    # NOTE (T-12 fix): a bare function assigned to a class attribute auto-binds
    # as a method via self.cost_provider, injecting an extra `self` arg and
    # raising on every call (silently swallowed, degrading to counts-mode).
    _Handler.cost_provider = staticmethod(cost_provider)

    server = _dashboard_server.DashboardServer(("127.0.0.1", 0), _Handler)
    t = threading.Thread(target=server.serve_forever, daemon=True)
    t.start()
    return server, t


def _get(server, path: str):
    port = server.server_address[1]
    conn = http.client.HTTPConnection("127.0.0.1", port, timeout=5)
    conn.request("GET", path)
    resp = conn.getresponse()
    body = resp.read()
    conn.close()
    return resp.status, body


# ---------------------------------------------------------------------------
# HOP 1-2-3: provider -> _task_summary merge whitelist -> scan_tasks/task_detail
# ---------------------------------------------------------------------------

def test_hop123_scan_tasks_emits_partial_true_for_mixed_ledger(tmp_path):
    """A drop at HOP 2 (removing 'partial' from the dashboard_model merge
    whitelist) fails HERE — this asserts through the emitted scan_tasks dict,
    not the provider's raw return."""
    project_root = _make_mixed_project(tmp_path)
    empty_home = tmp_path / "empty-home"  # no JSONL tree — proves inline path
    provider = make_cost_provider(project_root, home=empty_home)

    result = scan_tasks(project_root, cost_provider=provider)
    tasks = {t["name"]: t for t in result["tasks"]}
    assert "mixed-task" in tasks
    cost = tasks["mixed-task"]["cost"]
    assert cost["mode"] == "usd"
    assert cost["usd"] == pytest.approx(1.25)
    assert cost["partial"] is True, (
        "HOP 2/3 FAILED: 'partial' did not survive dashboard_model._task_summary "
        "into the scan_tasks-emitted cost dict"
    )


def test_hop123_task_detail_emits_partial_true_for_mixed_ledger(tmp_path):
    project_root = _make_mixed_project(tmp_path)
    empty_home = tmp_path / "empty-home"
    provider = make_cost_provider(project_root, home=empty_home)

    detail = task_detail(project_root, "mixed-task", cost_provider=provider)
    assert detail["cost"]["partial"] is True, "HOP 2/3 FAILED at task_detail"
    assert detail["cost"]["usd"] == pytest.approx(1.25)


# ---------------------------------------------------------------------------
# HOP 4: dashboard_server.py /api/tasks* json.dumps pass-through
# ---------------------------------------------------------------------------

def test_hop4_api_tasks_json_carries_partial_true(tmp_path):
    """A hypothetical server-side cost-key re-filter would fail HERE."""
    project_root = _make_mixed_project(tmp_path)
    empty_home = tmp_path / "empty-home"
    provider = make_cost_provider(project_root, home=empty_home)

    server, _ = _start_server(project_root, provider)
    try:
        status, body = _get(server, "/api/tasks")
        assert status == 200
        payload = json.loads(body)
        tasks = {t["name"]: t for t in payload["tasks"]}
        assert tasks["mixed-task"]["cost"]["partial"] is True, (
            "HOP 4 FAILED: /api/tasks JSON body dropped 'partial' on the wire"
        )

        status2, body2 = _get(server, "/api/tasks/mixed-task")
        assert status2 == 200
        detail_payload = json.loads(body2)
        assert detail_payload["cost"]["partial"] is True, (
            "HOP 4 FAILED: /api/tasks/<name> JSON body dropped 'partial' on the wire"
        )
    finally:
        server.shutdown()


def test_hop4_resolved_zero_survives_to_json(tmp_path):
    """MINOR-5/D-8 corollary at HOP 4: a resolved usd=0.0 must reach the wire
    as mode=usd/usd=0.0, not None/counts."""
    project_root = _make_resolved_zero_project(tmp_path)
    empty_home = tmp_path / "empty-home"
    provider = make_cost_provider(project_root, home=empty_home)

    server, _ = _start_server(project_root, provider)
    try:
        status, body = _get(server, "/api/tasks/zero-task")
        assert status == 200
        payload = json.loads(body)
        assert payload["cost"]["mode"] == "usd"
        assert payload["cost"]["usd"] == 0.0
        assert payload["cost"]["partial"] is False
    finally:
        server.shutdown()


# ---------------------------------------------------------------------------
# HOP 5: dashboard_assets/app.js render (source assertion — no DOM runner,
# per the repo's established app.js test idiom, test_dashboard_server.py:418)
# ---------------------------------------------------------------------------

def test_hop5_appjs_renders_partial_at_all_three_sites():
    """A drop of ANY of the three T-11 renders fails this hop distinctly
    from the badge/detail/caption sub-checks below."""
    source = _APP_JS_PATH.read_text(encoding="utf-8")

    # (a) cost badge
    assert "t.cost && t.cost.partial" in source, (
        "HOP 5 FAILED at the cost badge: no reference to t.cost.partial"
    )
    # (b) detail cost stat
    assert "detail.cost && detail.cost.partial" in source, (
        "HOP 5 FAILED at the detail cost stat: no reference to detail.cost.partial"
    )
    # (c) by-phase caption
    assert "cost.partial" in source and "ssPartialHtml" in source, (
        "HOP 5 FAILED at the by-phase caption: no reference to cost.partial"
    )
    # All three reuse the existing spend-unattrib idiom — no new CSS class.
    assert source.count("spend-unattrib") >= 4, (
        "Expected the existing 'spend-unattrib' class reused at the 3 new "
        "sites plus the pre-existing spend-monitor snapshot use (>=4 total)"
    )


def test_hop5_appjs_gate_relaxed_to_usd_not_null_minor5():
    """MINOR-5/D-8 at the render surface: the badge/detail usd-mode gate must
    be `usd != null` (not `usd > 0`) so a resolved $0.00 renders. A mutation
    re-adding '> 0' to either gate FAILS this."""
    source = _APP_JS_PATH.read_text(encoding="utf-8")

    assert "t.cost.usd != null && t.cost.usd > 0" not in source, (
        "Regression: the cost-badge usd gate still has the '> 0' clause — "
        "a resolved $0.00 would collapse to a row-count fallback"
    )
    assert "detail.cost.usd != null && detail.cost.usd > 0" not in source, (
        "Regression: the detail-stat usd gate still has the '> 0' clause"
    )
    # Positive confirmation the relaxed gates are actually present.
    assert "t.cost.mode === 'usd' && t.cost.usd != null" in source
    assert "detail.cost.mode === 'usd' && detail.cost.usd != null" in source


# ---------------------------------------------------------------------------
# Regression guard: cost_provider must be assigned via staticmethod() at the
# ACTUAL production call site (main()), not just in this test's harness —
# discovered while building this HOP-4 test (a bare function assigned to a
# class attribute auto-binds as a method via self.cost_provider, silently
# breaking every real cost_provider call in production dashboard_server.py).
# ---------------------------------------------------------------------------

def test_dashboard_server_main_wraps_cost_provider_in_staticmethod():
    source = (_ADAPTER_SCRIPTS / "dashboard_server.py").read_text(encoding="utf-8")
    assert "DashboardHandler.cost_provider = staticmethod(provider)" in source, (
        "Regression: DashboardHandler.cost_provider must be assigned via "
        "staticmethod() — a bare function assignment auto-binds as a method "
        "when accessed via self.cost_provider, silently raising TypeError on "
        "every call and degrading the real dashboard to counts-mode forever."
    )


def test_hop5_no_eventsource_regression_and_module_loadable():
    """Sanity: the app.js file this hop reads from actually exists and is
    the deployed core asset (not a stale copy) — guards against a typo'd path
    silently reading nothing and passing vacuously."""
    assert _APP_JS_PATH.is_file(), f"app.js not found at {_APP_JS_PATH}"
    assert _APP_JS_PATH.stat().st_size > 1000, "app.js unexpectedly tiny — wrong file?"
