"""Tests for IVG-164 stage 1 T-03: workflow-catalog.md registration.

Mirrors test_eod_refresh_routine_registered.py / test_discovery_refresh_routine.py's
AST-based TIER1_MEMORY_FILES registration check. TIER1_MEMORY_FILES is an
explicit allow-list consumed by BOTH deploy_memory() and compute_drift() in
src/quoin/installer.py, and a new memory/ file omitted from the tuple silently
never deploys — deploy_memory() sys.exit(1)s on a missing source file, so this
file (created in the SAME commit) must exist too.

workflow-catalog.md is the first GENERATED member of TIER1_MEMORY_FILES
(generated by quoin/scripts/build_claude_slim.py, landing in a later commit of
this stage). Three assertions, per T-03's acceptance:
  (a) the literal is present in the TIER1_MEMORY_FILES assignment
  (b) quoin/memory/workflow-catalog.md exists
  (c) the filename appears in quoin/memory/tier1-files.md

Assertion (c) closes the direction test_eod_refresh_routine_registered.py's own
docstring flags as deliberately uncovered ("Do not rely on tier1-files.md ... as
a substitute for this registration check") — correct as far as it goes, but
nothing before this test enforced the reverse (roster entry -> tier1-files.md
entry) for a generated file.
"""
from __future__ import annotations

import ast
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[3]  # quoin/
_SOURCE_ROOT = _REPO_ROOT / "quoin"

_CATALOG = _SOURCE_ROOT / "memory" / "workflow-catalog.md"
_TIER1_FILES_DOC = _SOURCE_ROOT / "memory" / "tier1-files.md"
_INSTALLER = _REPO_ROOT / "src" / "quoin" / "installer.py"


def _tier1_memory_files() -> list[str]:
    source = _INSTALLER.read_text(encoding="utf-8")
    tree = ast.parse(source)
    tier1: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "TIER1_MEMORY_FILES":
                    if isinstance(node.value, ast.Tuple):
                        tier1 = [
                            elt.value
                            for elt in node.value.elts
                            if isinstance(elt, ast.Constant) and isinstance(elt.value, str)
                        ]
    return tier1


def test_workflow_catalog_registered_in_tier1_memory_files() -> None:
    """(a) 'workflow-catalog.md' must be in TIER1_MEMORY_FILES in installer.py."""
    tier1 = _tier1_memory_files()
    assert "workflow-catalog.md" in tier1, (
        "'workflow-catalog.md' not found in TIER1_MEMORY_FILES in installer.py"
    )


def test_workflow_catalog_file_exists() -> None:
    """(b) quoin/memory/workflow-catalog.md must exist.

    Ordering matters: deploy_memory() sys.exit(1)s on a TIER1_MEMORY_FILES
    entry with no source file, breaking every install. This file is created
    in the same commit as the registration above.
    """
    assert _CATALOG.exists(), f"workflow-catalog.md not found: {_CATALOG}"


def test_workflow_catalog_listed_in_tier1_files_doc() -> None:
    """(c) 'workflow-catalog.md' must appear in quoin/memory/tier1-files.md.

    Closes the reverse direction: a roster entry with no tier1-files.md entry
    would leave the human-facing catalog silently incomplete.
    """
    text = _TIER1_FILES_DOC.read_text(encoding="utf-8")
    assert "workflow-catalog.md" in text, (
        "'workflow-catalog.md' not mentioned in quoin/memory/tier1-files.md"
    )
