"""IVG-258 stage 5 T-05: compaction_telemetry.py reader unit tests.

Shape mirrors test_run_state_writer.py: subprocess the reader and the two
shell hooks against tmp_path, assert on stdout/JSON. No LLM calls.

Reader units run over sinks *generated by running the hooks* wherever
possible — a committed/hand-authored fixture is suspect until reproduced
end-to-end from the shipped code path (round-1 critic precedent). The
ambiguity fixture's second case is hand-authored by necessity (asserting a
same-file key collision the hooks themselves only produce once
QUOIN_TELEMETRY_MAX_BYTES is raised past the 1 MiB tail window).
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
READER = REPO_ROOT / "quoin" / "core" / "scripts" / "compaction_telemetry.py"
HOOK_PRE = REPO_ROOT / "quoin" / "hooks" / "precompact.sh"
HOOK_POST = REPO_ROOT / "quoin" / "hooks" / "postcompact.sh"
RUN_STATE = REPO_ROOT / "quoin" / "core" / "scripts" / "run_state.py"

PY = sys.executable


def _run_reader(project_root: Path, *extra_args, env=None) -> dict:
    full_env = dict(os.environ)
    if env:
        full_env.update(env)
    result = subprocess.run(
        [PY, str(READER), "--project-root", str(project_root), "--format", "json", *extra_args],
        capture_output=True,
        text=True,
        timeout=30,
        env=full_env,
    )
    assert result.returncode == 0, f"reader exited {result.returncode}: {result.stderr}"
    return json.loads(result.stdout)


def _make_stdin_pre(session_id: str, cwd: Path, trigger: str = "auto") -> str:
    return json.dumps(
        {
            "trigger": trigger,
            "session_id": session_id,
            "cwd": str(cwd),
            "transcript_path": str(cwd / "dummy.jsonl"),
        }
    )


def _make_stdin_post(session_id: str, cwd: Path, transcript: Path) -> str:
    return json.dumps(
        {
            "session_id": session_id,
            "cwd": str(cwd),
            "transcript_path": str(transcript),
            "hook_event_name": "PostCompact",
        }
    )


def _drive_pair(cwd: Path, session_id: str, transcript: Path, env=None) -> None:
    full_env = dict(os.environ)
    if env:
        full_env.update(env)
    subprocess.run(
        ["sh", str(HOOK_PRE)],
        input=_make_stdin_pre(session_id, cwd),
        capture_output=True,
        text=True,
        timeout=15,
        env=full_env,
    )
    subprocess.run(
        ["sh", str(HOOK_POST)],
        input=_make_stdin_post(session_id, cwd, transcript),
        capture_output=True,
        text=True,
        timeout=15,
        env=full_env,
    )


def _sink_path(project_root: Path) -> Path:
    return project_root / ".workflow_artifacts" / "memory" / "telemetry" / "compaction-events.jsonl"


# ─── reader units over hook-generated sinks ──────────────────────────────────


def test_reader_basic_pair_from_real_hooks(tmp_path):
    transcript = tmp_path / "dummy.jsonl"
    transcript.write_text('{"type":"message"}\n')
    _drive_pair(tmp_path, "sess-basic", transcript)

    report = _run_reader(tmp_path)
    assert report["matched"] == 1
    assert report["ambiguous"] == 0
    assert report["pre_only"] == 0
    assert report["post_only"] == 0
    assert report["malformed"] == 0
    assert report["pre"] == 1
    assert report["post"] == 1


def test_reader_truncated_line_counts_malformed(tmp_path):
    transcript = tmp_path / "dummy.jsonl"
    transcript.write_text('{"type":"message"}\n')
    _drive_pair(tmp_path, "sess-truncate", transcript)

    sink = _sink_path(tmp_path)
    lines = sink.read_text().splitlines()
    assert len(lines) == 2
    lines[0] = lines[0][: len(lines[0]) // 2]  # truncate the pre line mid-JSON
    sink.write_text("\n".join(lines) + "\n")

    report = _run_reader(tmp_path)
    assert report["malformed"] == 1
    assert report["pre"] == 0
    assert report["post"] == 1
    assert report["post_only"] == 1


def test_reader_missing_post_is_pre_only(tmp_path):
    transcript = tmp_path / "dummy.jsonl"
    transcript.write_text('{"type":"message"}\n')
    _drive_pair(tmp_path, "sess-nopost", transcript)

    sink = _sink_path(tmp_path)
    lines = sink.read_text().splitlines()
    pre_line = [l for l in lines if '"half":"pre"' in l]
    sink.write_text("\n".join(pre_line) + "\n")

    report = _run_reader(tmp_path)
    assert report["matched"] == 0
    assert report["pre_only"] == 1
    assert report["post_only"] == 0


def test_reader_schema_forward_line_excluded(tmp_path):
    transcript = tmp_path / "dummy.jsonl"
    transcript.write_text('{"type":"message"}\n')
    _drive_pair(tmp_path, "sess-schema", transcript)

    sink = _sink_path(tmp_path)
    lines = sink.read_text().splitlines()
    bumped = []
    for line in lines:
        obj = json.loads(line)
        if obj.get("half") == "pre":
            obj["v"] = 2
        bumped.append(json.dumps(obj))
    sink.write_text("\n".join(bumped) + "\n")

    report = _run_reader(tmp_path)
    assert report["schema_forward"] == 1
    assert report["pre"] == 0
    assert report["post"] == 1
    assert report["post_only"] == 1


def test_reader_help_exits_zero():
    result = subprocess.run([PY, str(READER), "--help"], capture_output=True, text=True, timeout=15)
    assert result.returncode == 0


def test_reader_missing_sink_empty_report_exit_zero(tmp_path):
    (tmp_path / ".workflow_artifacts" / "memory").mkdir(parents=True)
    result = subprocess.run(
        [PY, str(READER), "--project-root", str(tmp_path), "--format", "json"],
        capture_output=True,
        text=True,
        timeout=15,
    )
    assert result.returncode == 0
    report = json.loads(result.stdout)
    assert report["pre"] == 0 and report["post"] == 0


# ─── ambiguity / tie-break unit ──────────────────────────────────────────────


def test_ambiguity_tie_break_rotation_fixture(tmp_path):
    """Drives the (T-01-rotate) shape: four compactions under a small
    QUOIN_TELEMETRY_MAX_BYTES so the sink rotates. The per-file tie-break
    resolves the guaranteed same-key collision without cross-file merging
    (round-1 critic MAJ-4) — round-3 critic MIN-1: only pairs 3 and 4
    survive on disk (mv -f overwrites .1 each time), so matched == 2."""
    transcript = tmp_path / "dummy.jsonl"
    transcript.write_text('{"type":"message"}\n')
    env = {"QUOIN_TELEMETRY_MAX_BYTES": "200"}
    for _ in range(4):
        _drive_pair(tmp_path, "sess-rotate", transcript, env=env)

    report = _run_reader(tmp_path)
    assert report["ambiguous"] == 0
    assert report["matched"] == 2


def test_ambiguity_hand_authored_collision(tmp_path):
    """A same-file (session_id, event_seq) collision the hooks themselves
    can also produce once QUOIN_TELEMETRY_MAX_BYTES exceeds the 1 MiB tail
    window (round-2 critic MIN-3) — hand-authored here for fixture
    convenience, not because it is hook-impossible."""
    tel_dir = tmp_path / ".workflow_artifacts" / "memory" / "telemetry"
    tel_dir.mkdir(parents=True)
    sink = tel_dir / "compaction-events.jsonl"
    records = [
        {"v": 1, "half": "pre", "session_id": "sess-collide", "event_seq": 0, "ts": "2026-01-01T00:00:00Z"},
        {"v": 1, "half": "pre", "session_id": "sess-collide", "event_seq": 0, "ts": "2026-01-01T00:00:01Z"},
        {"v": 1, "half": "post", "session_id": "sess-collide", "event_seq": 0, "ts": "2026-01-01T00:00:02Z"},
        {"v": 1, "half": "pre", "session_id": "sess-collide", "event_seq": 1, "ts": "2026-01-01T00:00:03Z"},
        {"v": 1, "half": "post", "session_id": "sess-collide", "event_seq": 1, "ts": "2026-01-01T00:00:04Z"},
    ]
    sink.write_text("\n".join(json.dumps(r) for r in records) + "\n")

    report = _run_reader(tmp_path)
    assert report["ambiguous"] == 3
    assert report["matched"] == 1
    assert report["pre_only"] == 0
    assert report["post_only"] == 0


# ─── end-to-end pair with a planted run-state record ─────────────────────────

_JQ_MISSING = pytest.mark.skipif(
    __import__("shutil").which("jq") is None, reason="jq required by the hooks"
)


@_JQ_MISSING
def test_end_to_end_pair_with_run_state(tmp_path):
    transcript = tmp_path / "dummy.jsonl"
    transcript.write_text('{"type":"message"}\n')

    subprocess.run(
        [
            PY, str(RUN_STATE), "--write", "--project-root", str(tmp_path),
            "--task", "tel-e2e", "--session-id", "sess-tel-e2e",
            "--phase", "implement", "--subphase", "code", "--step", "e2e step",
        ],
        capture_output=True, text=True, timeout=15,
    )
    _drive_pair(tmp_path, "sess-tel-e2e", transcript)

    sink = _sink_path(tmp_path)
    lines = [json.loads(l) for l in sink.read_text().splitlines() if l.strip()]
    pre = next(r for r in lines if r["half"] == "pre")
    post = next(r for r in lines if r["half"] == "post")
    assert pre["session_id"] == post["session_id"] == "sess-tel-e2e"
    assert pre["event_seq"] == post["event_seq"]
    assert pre["task"] == "tel-e2e"
    assert pre["phase"] == "implement"
    assert pre["subphase"] == "code"
    assert pre["step"] == "e2e step"

    report = _run_reader(tmp_path)
    assert report["matched"] == 1
    assert report["by_task"].get("tel-e2e") == 1


# ─── hook source contract (environment-independent) ──────────────────────────


def _postcompact_text() -> str:
    return HOOK_POST.read_text()


def _precompact_text() -> str:
    return HOOK_PRE.read_text()


def test_postcompact_source_contract():
    text = _postcompact_text()
    assert '--arg half "post"' in text
    assert "read_constants" in text
    # No printf line interpolates $session_id directly into a hand-built
    # `{`-shaped JSON string — every emitted value goes through jq --arg.
    for line in text.splitlines():
        if "printf" in line and "{" in line and "$session_id" in line:
            pytest.fail(f"hand-built JSON interpolating $session_id: {line!r}")
    # .allow-compact check precedes the rest of STEP 3's work.
    step3_idx = text.index("# STEP 3: Telemetry")
    marker_idx = text.index('[ -f "${cwd}/.allow-compact" ] && exit 0')
    assert marker_idx > step3_idx, "marker check must be inside/after STEP 3's own comment"
    # it must be the FIRST statement inside the STEP 3 subshell body
    subshell_open_idx = text.index("(\n", step3_idx)
    between = text[subshell_open_idx:marker_idx]
    assert between.strip().endswith("") or "_tel_dir=" not in between, (
        "the .allow-compact check must be the first statement inside the STEP 3 subshell"
    )


def _rotation_landmark_offsets(text: str) -> tuple[int, int, int]:
    """Return (hardlink_probe_offset, dot1_probe_offset, mv_offset), each the
    landmark's own first offset from position 0 (round-1 critic MAJ-1: never
    anchor relative to another landmark — that can pass tautologically)."""
    hardlink_probe = text.index('printf \'[quoin-precompact] WARNING: telemetry sink refused (hard link)')
    dot1_probe = text.index('[ -e "${_tel_sink}.1" ] || [ -L "${_tel_sink}.1" ]')
    mv_stmt = text.index('if ! mv -f "$_tel_sink" "${_tel_sink}.1"')
    tel_esc = text.index('_tel_esc=$(jq -nc --arg s "$session_id"')
    return hardlink_probe, dot1_probe, mv_stmt, tel_esc


def test_precompact_rotation_ordering_contract():
    text = _precompact_text()
    hardlink_probe, dot1_probe, mv_stmt, tel_esc = _rotation_landmark_offsets(text)
    assert hardlink_probe < dot1_probe < mv_stmt < tel_esc, (
        "rotation must sit after the hard-link refusal and before the "
        "_tel_esc session-id probe, with its own .1 probe ahead of the mv"
    )


# ─── mutation probe: rotation moved after _tel_esc ───────────────────────────


def test_mutation_probe_rotation_after_tel_esc_fails(tmp_path):
    """Move the rotation block after the _tel_esc line in a scratch copy and
    confirm the ordering assertion fails — a guard that still passes under
    the mutation is not pinning what it claims."""
    text = _precompact_text()
    block_start = text.index("  _tel_max=${TELEMETRY_MAX_BYTES:-1048576}")
    block_end = text.index('_tel_esc=$(jq -nc --arg s "$session_id"')
    rotation_block = text[block_start:block_end]
    tel_esc_line_end = text.index("\n", block_end) + 1
    tel_esc_line = text[block_end:tel_esc_line_end]

    mutated = text[:block_start] + tel_esc_line + rotation_block + text[tel_esc_line_end:]
    hardlink_probe, dot1_probe, mv_stmt, tel_esc = _rotation_landmark_offsets(mutated)
    assert not (hardlink_probe < dot1_probe < mv_stmt < tel_esc), (
        "mutation did not move rotation after _tel_esc as intended"
    )
